### PR TITLE
Add portability tests on GH Actions using Sage

### PR DESCRIPTION
**Pull request by mkoeppe**
Preview: https://github.com/mkoeppe/cmr/actions/runs/5338160163

(all `-minimal` configurations fail because Sage is bringing an ancient version of boost; all `-standard` configurations fail because of #29; fixed by #30)

### CODE REVIEW

**Comment by discopt** [comment]
> Preview: https://github.com/mkoeppe/cmr/actions/runs/5338160163
> 
> (all `-minimal` configurations fail because Sage is bringing an ancient version of boost; all `-standard` configurations fail because of #29; fixed by #30)

The most recent implementation of the tests for TU and network matrices are written entirely in C. C++ is only still there because of some other tests for which some linear algebra (mostly LU factorization) are needed. Would it make sense to create a branch where these are disabled and thus the C++/boost dependency is gone?

**Comment by mkoeppe** [comment]
No need to make a special branch for Sage. We need to update our boost anyway; I'll look into it today.

**Comment by mkoeppe** [comment]
OK, the problem is solved. Actually I had just forgotten to declare the dependency on boost on the Sage side of things.

The failures are now all test suite failures:
```
  [cmr-git]           Start 108: TotallyUnimodular.ForbiddenSubmatrix
  [cmr-git]   108/108 Test #108: TotallyUnimodular.ForbiddenSubmatrix ....................***Failed    0.01 sec
  [cmr-git]   
  [cmr-git]   99% tests passed, 1 tests failed out of 108
  [cmr-git]   
  [cmr-git]   Total Test time (real) =   0.95 sec
  [cmr-git]   
  [cmr-git]   The following tests FAILED:
  [cmr-git]   	108 - TotallyUnimodular.ForbiddenSubmatrix (Failed)
  [cmr-git]   Errors while running CTest
  [cmr-git]   Output from these tests are in: /sage/local/var/tmp/sage/build/cmr-git/src/build/Testing/Temporary/LastTest.log
  [cmr-git]   Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
  [cmr-git]   
```

**Comment by discopt** [comment]
@mkoeppe I'm still new to github CI: Merging this to master would imply that any pushed commits trigger that the sage-CMR interface is tested against the updated CMR code?

**Pull request merged**
